### ISSUE TITLE
Require support with single click pull to refresh

### ISSUE THREAD

**Issue by KMSoft2013** [IsaacXen/IXRefreshableScrollView#5]
Require support with single click pull to refresh as current version doesn't allow pull to refresh if user don't have track pad for iMac user.

For current we need to use two finger gesture with trackpad.

**Comment by IsaacXen** [comment]
I believe you could trigger pull to refresh programmatically just by calling:

```swift
scrollView.beginRefreshing(scrollToTop: true)
```

This is tested on MBP since that's the only device I have, but it should works on any devices.

There're still some glitches when passing `false` as the first parameter, but it should works fine if you pass `true`.
